WHITE = 0
BLACK = 1

PAWN = 0
KNIGHT = 1
BISHOP = 2
ROOK = 3
QUEEN = 4
KING = 5

UP = 0
DOWN = 1
LEFT = 2
RIGHT = 3
UP_LEFT = 4
UP_RIGHT = 5
DOWN_LEFT = 6
DOWN_RIGHT = 7

FEN_INIT = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 0'
FEN_CLEAN = '8/8/8/8/8/8/8/8 w - - 0 0'


COLOR_BG_LIGHT_BASIC = '#EDEAE0'
COLOR_BG_DARK_BASIC = '#8F9779'

#COLOR_BG_LIGHT_SELECTED = '#FFBAB0'
COLOR_BG_DARK_SELECTED = '#FF9779'
COLOR_BG_LIGHT_SELECTED = '#FF9779'


COLOR_BG_LIGHT_LIGHTED = '#CCCCFF'
COLOR_BG_DARK_LIGHTED = '#CCCCFF'
